version: '5'
services:
  kafka:
    image: lifeway/kafka:0.8.2.1_2.11
    container_name: kafka
    ports:
      - "9092:9092"
  
  spark-streaming:
    build: ./spark-streaming
    container_name: spark-streaming
    depends_on:
      - kafka
      - database

  streaming-app:
    build: ./streaming-app
    container_name: streaming-app
    depends_on:
      - kafka

  database:
    build: ./database
    container_name: database
    ports:
      - "5432:5432"

  speed_layer_api:
    build: ./speed_layer_api
    container_name: speed_layer_api
    depends_on:
      - database
    environment:
      - DATABASE_NAME=database
      - DATABASE_PASSWORD=secret
    ports:
      - "8000:8000"
